#!/usr/bin/env bash

# fix segmentation fault reported in https://github.com/k2-fsa/icefall/issues/674
export PROTOCOL_BUFFERS_PYTHON_IMPLEMENTATION=python

set -eou pipefail

nj=15
stage=0
stop_stage=5

# We assume dl_dir (download dir) contains the following
# directories and files. If not, they will be downloaded
# by this script automatically.
dl_dir=$PWD/download

. shared/parse_options.sh || exit 1

# All files generated by this script are saved in "data".
# You can safely remove "data" and rerun this script to regenerate it.
mkdir -p data

log() {
  # This function is from espnet
  local fname=${BASH_SOURCE[1]##*/}
  echo -e "$(date '+%Y-%m-%d %H:%M:%S') (${fname}:${BASH_LINENO[0]}:${FUNCNAME[1]}) $*"
}

log "Running prepare.sh for Bud500"
log "dl_dir: $dl_dir"

if [ $stage -le -1 ] && [ $stop_stage -ge -1 ]; then
  log "Stage -1: Download LM"
  mkdir -p $dl_dir/lm
  if [ ! -e $dl_dir/lm/.done ]; then
    ./local/download_lm.py --out-dir=$dl_dir/lm
    touch $dl_dir/lm/.done
  fi
fi

if [ $stage -le 0 ] && [ $stop_stage -ge 0 ]; then
  log "Stage 0: Preparing Bud500 Data and MUSAN"

  # [MODIFICATION] Run your custom python script
  # This handles Download, Manifests, Fbank Extraction, and BPE Training
  log "Running local/prepare_bud500.py..."
  python3 local/prepare_bud500.py \
    --output-dir data \
    --vocab-size 500

  # [KEEPING] MUSAN is required for data augmentation in most Icefall recipes
  if [ ! -d $dl_dir/musan ]; then
    lhotse download musan $dl_dir
  fi
fi

if [ $stage -le 1 ] && [ $stop_stage -ge 1 ]; then
  log "Stage 1: Prepare LibriSpeech manifest (Skipped - handled by prepare_bud500.py)"
fi

if [ $stage -le 2 ] && [ $stop_stage -ge 2 ]; then
  log "Stage 2: Prepare musan manifest"
  mkdir -p data/manifests
  if [ ! -e data/manifests/.musan.done ]; then
    lhotse prepare musan $dl_dir/musan data/manifests
    touch data/manifests/.musan.done
  fi
fi

if [ $stage -le 3 ] && [ $stop_stage -ge 3 ]; then
  log "Stage 3: Compute fbank for librispeech (Skipped - handled by prepare_bud500.py)"
  
  # [CRITICAL STEP] Symlink Bud500 files to LibriSpeech filenames
  # This allows the standard train.py to run without modification.
  log "Creating symlinks to map Bud500 to LibriSpeech filenames..."
  
  mkdir -p data/fbank
  cd data/fbank
  
  # 1. Map our single TRAIN set to 'train-clean-100'
  # We will tell the training script to ONLY use this subset.
  ln -sf bud500_cuts_train.jsonl.gz librispeech_cuts_train-clean-100.jsonl.gz
  
  # 2. Map our DEV set to standard LibriSpeech dev sets
  ln -sf bud500_cuts_dev.jsonl.gz librispeech_cuts_dev-clean.jsonl.gz
  ln -sf bud500_cuts_dev.jsonl.gz librispeech_cuts_dev-other.jsonl.gz
  
  # 3. Map our TEST set to standard LibriSpeech test sets
  ln -sf bud500_cuts_test.jsonl.gz librispeech_cuts_test-clean.jsonl.gz
  ln -sf bud500_cuts_test.jsonl.gz librispeech_cuts_test-other.jsonl.gz
  
  cd ../..
  
  # Create a validation marker so the script doesn't complain
  touch data/fbank/.librispeech-validated.done
fi

if [ $stage -le 4 ] && [ $stop_stage -ge 4 ]; then
  log "Stage 4: Compute fbank for musan"
  mkdir -p data/fbank
  if [ ! -e data/fbank/.musan.done ]; then
    ./local/compute_fbank_musan.py
    touch data/fbank/.musan.done
  fi
fi

if [ $stage -le 5 ] && [ $stop_stage -ge 5 ]; then
  log "Stage 5: Prepare BPE based lang (Skipped - handled by prepare_bud500.py)"
fi
